[project]
name = "rpkgkit"
r_version = ">=4.1.0"
description = "Create and Maintain R Packages"

[dependencies]
cli = "*"
lifecycle = "*"
rlang = ">=1.0.0"
rstudioapi = "*"

[dev-dependencies]
desc = "*"
devtools = "*"
dplyr = "*"
flir = "*"
gh = "*"
grDevices = "*"
httr2 = "*"
knitr = "*"
pkgload = "*"
rmarkdown = "*"
stats = "*"
testthat = ">=3.0.0"
usethis = "*"
withr = "*"
yaml = "*"
