#' @rdname convert_int_literals
#' @export
package_convert_int_literals <- function(
  path = NULL,
  dirs = c("R"),
  recursive = TRUE,
  ...
) {
  rlang::check_dots_empty(...)
  rlang::check_bool(recursive)

  path <- path %||% "."

  if (!is_pkg(path)) {
    cli::cli_abort(c(
      "x" = "{.path {path}} does not look like an R package root.",
      "i" = "Expected a {.file DESCRIPTION} file."
    ))
  }

  path <- normalizePath(path, winslash = "/", mustWork = TRUE)

  files <- character()
  for (d in dirs) {
    dir_path <- file.path(path, d)
    if (!dir.exists(dir_path)) {
      next
    }
    files <- c(
      files,
      list.files(
        dir_path,
        pattern = "\\.[Rr]$",
        full.names = TRUE,
        recursive = recursive
      )
    )
  }

  files <- unique(files)
  # Generated by Rcpp::compileAttributes(); manual edits are overwritten.
  files <- files[tolower(basename(files)) != "rcppexports.r"]

  n <- length(files)
  if (!n) {
    cli::cli_alert_info("No R files found under {.path {path}}")
    return(invisible(character()))
  }

  changed <- character()
  cli::cli_progress_bar(
    name = "Adding L suffixes",
    total = n,
    format = "{cli::pb_spin} Converting integer literals in package {cli::pb_current}/{cli::pb_total} | {cli::pb_percent}"
  )

  for (f in files) {
    cli::cli_progress_update(status = basename(f))
    original <- paste(readLines(f, warn = FALSE), collapse = "\n")
    convert_int_literals(path = f, verbose = FALSE)
    updated <- paste(readLines(f, warn = FALSE), collapse = "\n")
    if (!identical(original, updated)) {
      changed <- c(changed, f)
    }
  }

  cli::cli_progress_done()

  n_changed <- length(changed)
  cli::cli_alert_success(
    "Processed {n} file{?s}, updated {n_changed}"
  )

  invisible(changed)
}
