#' @rdname convert_pipe
#' @export
package_convert_pipe <- function(
  path = NULL,
  direction = c("to_base", "to_magrittr"),
  dirs = c("R"),
  recursive = TRUE,
  ...
) {
  rlang::check_dots_empty()
  direction <- rlang::arg_match(direction)
  rlang::check_bool(recursive)

  path <- path %||% "."

  if (!is_pkg(path)) {
    cli::cli_abort(c(
      "x" = "{.path {path}} does not look like an R package root.",
      "i" = "Expected a {.file DESCRIPTION} file."
    ))
  }

  path <- normalizePath(path, winslash = "/", mustWork = TRUE)

  files <- character()
  for (d in dirs) {
    dir_path <- file.path(path, d)
    if (!dir.exists(dir_path)) {
      next
    }
    files <- c(
      files,
      list.files(
        dir_path,
        pattern = "\\.[Rr]$",
        full.names = TRUE,
        recursive = recursive
      )
    )
  }

  # Generated by Rcpp::compileAttributes(); manual edits are overwritten.
  files <- files[tolower(basename(files)) != "rcppexports.r"]

  n <- length(files)
  if (!n) {
    cli::cli_alert_info("No R files found under {.path {path}}")
    return(invisible(FALSE))
  }

  n_changed <- 0L
  cli::cli_progress_bar(
    name = "Converting pipes",
    total = n,
    format = "{cli::pb_spin} Converting pipes in package {cli::pb_current}/{cli::pb_total} | {cli::pb_percent}"
  )

  for (f in files) {
    cli::cli_progress_update(status = basename(f))
    original <- paste(readLines(f, warn = FALSE), collapse = "\n")
    convert_pipe(path = f, direction = direction, verbose = FALSE)
    updated <- paste(readLines(f, warn = FALSE), collapse = "\n")
    if (!identical(original, updated)) {
      n_changed <- n_changed + 1L
    }
  }

  cli::cli_progress_done()
  cli::cli_alert_success(
    "Processed {n} file{?s}, updated {n_changed}"
  )

  if (n_changed > 0L) {
    invisible(TRUE)
  } else {
    invisible(FALSE)
  }
}
