# Standalone file: do not edit by hand
# Source: https://github.com/r-lib/rlang/blob/HEAD/R/standalone-zeallot.R
# Generated by: usethis::use_standalone("r-lib/rlang", "zeallot")
# ----------------------------------------------------------------------
#
# ---
# repo: r-lib/rlang
# file: standalone-zeallot.R
# last-updated: 2020-11-24
# license: https://unlicense.org
# imports: rlang
# ---
#
# This drop-in file implements a simple version of zeallot::`%<-%`.
#
# nocov start

`%<-%` <- function(lhs, value) {
  lhs <- substitute(lhs)
  env <- rlang::caller_env()

  if (!rlang::is_call(lhs, "c")) {
    rlang::abort("The left-hand side of `%<-%` must be a call to `c()`.")
  }

  vars <- as.list(lhs[-1L])

  if (length(value) != length(vars)) {
    rlang::abort("The left- and right-hand sides of `%<-%` must be the same length.")
  }

  for (i in seq_along(vars)) {
    var <- vars[[i]]
    if (!rlang::is_symbol(var)) {
      rlang::abort(paste0(
        "Element ",
        i,
        " of the left-hand side of `%<-%` must be a symbol."
      ))
    }

    env[[rlang::as_string(var)]] <- value[[i]]
  }

  invisible(value)
}

# nocov end
